Matrix.Web/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Matrix.Web.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Matrix.Web/Controllers/LogController.cs
using System;
using System.Threading.Tasks;
using Matrix.Framework.Constants;
using Matrix.Web.Business.Services;
using Matrix.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace Matrix.Web.Controllers
{
    public class LogController : Controller
    {
        public IApplicationService Registry { get; }

        public ILogService Server { get; }

        public LogController(IApplicationService registry, ILogService server)
        {
            Registry = registry ?? throw new ArgumentNullException(nameof(registry));
            Server = server ?? throw new ArgumentNullException(nameof(server));
        }

        [HttpGet]
        [Route("logs")]
        public async Task<IActionResult> Index()
        {
            IActionResult result = null;

            await Task.Run(() =>
            {
                result = RedirectToActionPermanent("Index", new { application = This.Id });
            });

            return result;
        }

        [HttpGet]
        [Route("applications/{application}/logs")]
        public async Task<IActionResult> Index(Guid application)
        {
            var model = new LogListViewModel()
            {
                Application = application,
                Applications = await Registry.GetApplications(),
                Logs = await Server.GetLogs(application, DateTime.Now.Subtract(new TimeSpan(1, 0, 0, 0)), DateTime.Now, 1, 10)
            };

            return View(model);
        }
    }
}

Matrix.Web/Controllers/MailController.cs
using System;
using System.Threading.Tasks;
using Matrix.Framework.Constants;
using Matrix.Web.Business.Services;
using Matrix.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace Matrix.Web.Controllers
{
    public class MailController : Controller
    {
        public IApplicationService Registry { get; }

        public IEmailService Server { get; }

        public MailController(IApplicationService registry, IEmailService server)
        {
            Registry = registry ?? throw new ArgumentNullException(nameof(registry));
            Server = server ?? throw new ArgumentNullException(nameof(server));
        }

        [HttpGet]
        [Route("emails")]
        public async Task<IActionResult> Index()
        {
            IActionResult result = null;

            await Task.Run(() =>
            {
                result = RedirectToActionPermanent("Index", new { application = This.Id });
            });

            return result;
        }

        [HttpGet]
        [Route("applications/{application}/emails")]
        public async Task<IActionResult> Index(Guid application)
        {
            var model = new EmailListViewModel()
            {
                Application = application,
                Applications = await Registry.GetApplications(),
                Emails = await Server.GetEmails(application, DateTime.Now.Subtract(new TimeSpan(1, 0, 0, 0)), DateTime.Now, 1, 10)
            };

            return View(model);
        }
    }
}

Matrix.Web/Controllers/UserController.cs
using System;
using System.Threading.Tasks;
using Matrix.Framework.Constants;
using Matrix.Web.Business.Services;
using Matrix.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace Matrix.Web.Controllers
{
    public class UserController : Controller
    {
        public IApplicationService Registry { get; }

        public IUserService Server { get; }

        public UserController(IApplicationService registry, IUserService server)
        {
            Registry = registry ?? throw new ArgumentNullException(nameof(registry));
            Server = server ?? throw new ArgumentNullException(nameof(server));
        }

        [HttpGet]
        [Route("users")]
        public async Task<IActionResult> Index()
        {
            IActionResult result = null;

            await Task.Run(() =>
            {
                result = RedirectToActionPermanent("Index", new { application = This.Id });
            });

            return result;
        }

        [HttpGet]
        [Route("applications/{application}/users")]
        public async Task<IActionResult> Index(Guid application)
        {
            var model = new UserListViewModel()
            {
                Application = application,
                Applications = await Registry.GetApplications(),
                Users = await Server.GetUsers(application)
            };

            return View(model);
        }
    }
}

Matrix.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Matrix</title>
    <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css" />
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js" crossorigin="anonymous" integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js" crossorigin="anonymous" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"></script>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Matrix</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Registry" asp-action="Index">Registry</a></li>
                    <li><a asp-area="" asp-controller="Configuration" asp-action="Index">Configuration</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Directory <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="User" asp-action="Index">User Profiles</a></li>
                            <li><a asp-area="" asp-controller="UserGroup" asp-action="Index">User Groups</a></li>
                            <li><a asp-area="" asp-controller="UserRole" asp-action="Index">User Roles</a></li>
                        </ul>
                    </li>
                    <li><a asp-area="" asp-controller="Log" asp-action="Index">Journal</a></li>
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Postman <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="Mail" asp-action="Index">Emails</a></li>
                            <li><a asp-area="" asp-controller="Phone" asp-action="Index">Phone Messages</a></li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a asp-area="" asp-controller="About" asp-action="Index">About</a></li>
                    <li><a asp-area="" asp-controller="Contact" asp-action="Index">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        <br />
        <br />
        <br />
        <br />
        @RenderBody()
    </div>
    <nav class="navbar navbar-inverse navbar-fixed-bottom">
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a asp-area="" asp-controller="Copyright" asp-action="Index">Copyright (C) 2018 Paramesh Gunasekaran. All Rights Reserved.</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a asp-area="" asp-controller="Terms" asp-action="Index">Terms</a></li>
                <li><a asp-area="" asp-controller="Privacy" asp-action="Index">Privacy</a></li>
                <li><a asp-area="" asp-controller="Contact" asp-action="Index">Contact&nbsp;&nbsp;&nbsp;</a></li>
            </ul>
        </div>
    </nav>
    @RenderSection("Scripts", required: false)
</body>
</html>