Matrix.Web/Controllers/UserGroupController.cs
using System;
using System.Threading.Tasks;
using Matrix.Framework.Constants;
using Matrix.Web.Business.Services;
using Matrix.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace Matrix.Web.Controllers
{
    public class UserGroupController : Controller
    {
        public IApplicationService Registry { get; }

        public IUserGroupService Server { get; }

        public UserGroupController(IApplicationService registry, IUserGroupService server)
        {
            Registry = registry ?? throw new ArgumentNullException(nameof(registry));
            Server = server ?? throw new ArgumentNullException(nameof(server));
        }

        [HttpGet]
        [Route("usergroups")]
        public async Task<IActionResult> Index()
        {
            IActionResult result = null;

            await Task.Run(() =>
            {
                result = RedirectToActionPermanent("Index", new { application = This.Id });
            });

            return result;
        }

        [HttpGet]
        [Route("applications/{application}/usergroups")]
        public async Task<IActionResult> Index(Guid application)
        {
            var model = new UserGroupListViewModel()
            {
                Application = application,
                Applications = await Registry.GetApplications(),
                UserGroups = await Server.GetUserGroups(application)
            };

            return View(model);
        }
    }
}

Matrix.Web/Views/UserGroup/Index.cshtml
@model UserGroupListViewModel

<div class="panel panel-default">
    <div class="panel-heading">
        <table border="0" width="100%">
            <tr>
                <td>
                    <h3 class="panel-title"><b>User Groups</b></h3>
                </td>
                <td style="text-align:right" width="200px">
                    <select class="form-control" id="application" name="application">
                        @foreach (var i in Model.Applications)
                        {
                            if (i.Id.Equals(Model.Application))
                            {

                                <option value="@i.Id" selected>@i.Name</option>
                            }
                            else
                            {
                                <option value="@i.Id">@i.Name</option>
                            }
                        }
                    </select>
                </td>
            </tr>
        </table>
    </div>
    <div class="panel-body">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <td width="50%"><b>Name</b></td>
                    <td width="50%"><b>Description</b></td>
                    <td style="text-align:center" width="10px"><span class="glyphicon glyphicon-trash"></span></td>
                </tr>
            </thead>
            <tbody>
                @foreach (var i in Model.UserGroups)
                {
                    <tr>
                        <td>@i.Name</td>
                        <td>@i.Description</td>
                        <td>
                            <button type="button" class="btn btn-xs btn-danger" disabled>
                                <span class="glyphicon glyphicon-remove"></span>
                            </button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<script>
    $("#application").change(function () {
        var app = $('#application').val();
        var url = "@this.Url.Action("Index", "UserGroup", new { application = "__appid__" })"
        window.location = url.replace("__appid__", app);
    });
</script>